import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { appInfo, root } from './webos-appinfo.mjs';

function run(command, args) {
    const result = spawnSync(command, args, { cwd: root, stdio: 'inherit' });
    if (result.error) throw new Error(`${command}: ${result.error.message}. Install @webos-tools/cli and add it to PATH.`);
    if (result.status !== 0) throw new Error(`${command} failed (${result.signal || result.status})`);
}
try {
    const args = process.argv.slice(2).filter(arg => arg !== '--');
    const hosted = args[0] === '--hosted';
    if (args.length && (!hosted || args.length !== 2)) throw new Error('Usage: package:webos [--hosted https://LAN-host/]');
    let hostedURL;
    if (hosted) {
        hostedURL = new URL(args[1]);
        if (!['http:', 'https:'].includes(hostedURL.protocol) || hostedURL.username || hostedURL.password) throw new Error('Hosted URL must be HTTP(S) without credentials');
        if (!hostedURL.pathname.endsWith('/') || hostedURL.search || hostedURL.hash) throw new Error('Hosted URL must end in / without query or fragment');
    } else {
        // Reject hosted, desktop and incomplete builds before changing staging.
        run(process.execPath, ['scripts/verify-webos-packaged-build.mjs']);
    }
    const mode = hosted ? 'hosted' : 'packaged';
    const stage = path.join(root, 'dist-webos', mode);
    const output = path.join(root, 'dist-webos', 'packages', mode);
    fs.rmSync(stage, { recursive: true, force: true });
    fs.mkdirSync(stage, { recursive: true });
    fs.mkdirSync(output, { recursive: true });
    if (hosted) {
        const target = JSON.stringify(hostedURL.href).replace(/</g, '\\u003c');
        fs.writeFileSync(path.join(stage, 'index.html'), `<!doctype html><html><head><meta charset="utf-8"><title>Stremio</title></head><body><script>location.replace(${target});</script></body></html>\n`);
    } else {
        fs.cpSync(path.join(root, 'build'), stage, { recursive: true, filter: source => !source.endsWith('.map') });
    }
    fs.cpSync(path.join(root, 'webos/assets'), path.join(stage, 'assets'), {
        recursive: true,
        filter: source => fs.statSync(source).isDirectory() || (source.endsWith('.png') && !source.endsWith('store_400x400.png'))
    });
    const info = appInfo();
    if (hosted) info.id += '.hosted';
    fs.writeFileSync(path.join(stage, 'appinfo.json'), `${JSON.stringify(info, null, 4)}\n`);
    // Preserve generated bytes: webpack already transpiles/minifies for Chromium 68.
    run('ares-package', ['--no-minify', stage, '--outdir', output]);
    const ipk = path.join(output, `${info.id}_${info.version}_all.ipk`);
    if (!fs.existsSync(ipk)) throw new Error(`CLI did not produce expected package: ${ipk}`);
    fs.writeFileSync(path.join(output, 'build-info.json'), `${JSON.stringify({ id: info.id, version: info.version, sourceVersion: JSON.parse(fs.readFileSync(path.join(root, 'package.json'))).version, mode, package: path.basename(ipk) }, null, 2)}\n`);
    console.log(`Package: ${ipk}`);
} catch (error) {
    console.error(error.message);
    process.exitCode = 1;
}
